//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelagencyEntities : DbContext
    {
        private static TravelagencyEntities _context;
        public TravelagencyEntities()
            : base("name=TravelagencyEntities")
        {
        }

        public static TravelagencyEntities GetContext()
        {
            if (_context == null)
                _context = new TravelagencyEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalServices> AdditionalServices { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<RestType> RestType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vouchers> Vouchers { get; set; }
    }
}
