//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public int Код_путевки { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_окончания { get; set; }
        public int Продолжительность { get; set; }
        public int Код_отеля { get; set; }
        public int Код_вида { get; set; }
        public int Код_услуги_1 { get; set; }
        public int Код_услуги_2 { get; set; }
        public int Код_услуги_3 { get; set; }
        public int Код_клиента { get; set; }
        public int Код_сотрудника { get; set; }
        public bool Отметка_о_бронировании { get; set; }
        public bool Отметка_об_оплате { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual AdditionalServices AdditionalServices1 { get; set; }
        public virtual AdditionalServices AdditionalServices2 { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Hotels Hotels { get; set; }
        public virtual RestType RestType { get; set; }
    }
}
